target_type: 'aprilgrid' #gridtype
tagCols: 3               #number of apriltags
tagRows: 4              #number of apriltags
tagSize: 0.2           #size of apriltag, edge to edge [m]
tagSpacing: 0.3          #ratio of space between tags to tagSize
                         #example: tagSize=2m, spacing=0.5m --> tagSpacing=0.25[-]
