#Accelerometer
accelerometer_noise_density: 0.0014126598501078217 
accelerometer_random_walk: 1.9005701759499173e-05 

#Gyroscope
gyroscope_noise_density: 7.77970988215584e-05 
gyroscope_random_walk: 3.3171207235534e-07 

rostopic: '/imu/imu_compensated' 
# rostopic: '/imu/imu_uncompensated' 
update_rate: 400.0 #Hz

